--
--# --- !Ups

-- -- floor_master
--INSERT INTO floor_master (floor_name, display_order, place_id) VALUES ('8F', 1, 1);
--INSERT INTO floor_master (floor_name, display_order, place_id) VALUES ('7F', 2, 1);
--INSERT INTO floor_master (floor_name, display_order, place_id) VALUES ('6F', 3, 1);
--INSERT INTO floor_master (floor_name, display_order, place_id) VALUES ('5F', 4, 1);
--INSERT INTO floor_master (floor_name, display_order, place_id) VALUES ('4F', 5, 1);
--INSERT INTO floor_master (floor_name, display_order, place_id) VALUES ('3F', 6, 1);
--INSERT INTO floor_master (floor_name, display_order, place_id) VALUES ('2F', 7, 1);
--INSERT INTO floor_master (floor_name, display_order, place_id) VALUES ('1F', 8, 1);
--
-- -- company_master
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト1', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト1', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト2', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('配管1', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('配管2', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('保温1', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('保温2', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('計装1', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('計装2', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('多能1', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('多能2', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト2', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト3', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト4', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト5', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト6', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト7', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト8', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト9', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト10', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト11', 1);
--INSERT INTO company_master (company_name, place_id) VALUES ('ダクト12', 1);

--# --- !Downs
--
