--
--# --- !Ups
--INSERT INTO user_master (email, name, password, place_id) VALUES ('exb@where123.jp', 'exb', '$2a$10$3Gyu0kfE2oaTHfQfg6saZ.9A3eCGBF.6enfUtA7jRv0Y9Qd3prGnK', null);
--
--# --- !Downs
--
